language: php

matrix:
  fast_finish: true
  include:
    - php: '7.1'
    - php: '7.2'
    - php: '7.3'
    - php: '7.4'
      after_script:
        - bash <(curl -s https://codecov.io/bash)
    - php: '7.4'
      name: 'Prefer lowest'
      install:
        - composer self-update --2
        - composer update --no-interaction --prefer-lowest
    - php: 'nightly'
      install:
        - composer update --no-interaction --ignore-platform-reqs
  allow_failures:
    - php: 'nightly'

addons:
 apt:
  packages:
   - apache2
   - libapache2-mod-fastcgi

cache:
  directories:
    - $HOME/.composer/cache/files

install:
  - composer update --no-interaction

before_script:
 - vendor/bin/phpunit --version
 # enable php-fpm
 - sudo cp ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.conf.default ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.conf
 - sudo a2enmod rewrite actions fastcgi alias
 - echo "cgi.fix_pathinfo = 1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
 - sudo sed -i -e "s,www-data,travis,g" /etc/apache2/envvars
 - sudo chown -R travis:travis /var/lib/apache2/fastcgi
 - ~/.phpenv/versions/$(phpenv version-name)/sbin/php-fpm
 # configure apache virtual hosts
 - sudo cp -f build/travis-ci-apache.conf /etc/apache2/sites-available/000-default.conf
 - sudo sed -e "s?%TRAVIS_BUILD_DIR%?$(pwd)?g" --in-place /etc/apache2/sites-available/000-default.conf
 - sudo service apache2 restart

script:
 - vendor/bin/phpunit
