language: php

matrix:
  fast_finish: true
  include:
    - php: '7.2'
    - php: '7.3'
    - php: '7.4'
      name: 'Prefer lowest'
      install:
        - composer self-update --2
        - composer update --no-interaction --prefer-lowest --no-cache
    - php: 'nightly'
      install:
        - composer install --no-interaction --ignore-platform-reqs --no-cache
  allow_failures:
    - php: 'nightly'

addons:
 apt:
  packages:
   - php-xml

install:
  - sudo ln -s tests/emulator /var/www/html/web
  - if [ "$IGNORE_PLATFORM_REQS" == 'true' ]; then composer install --no-interaction --ignore-platform-reqs;
    else composer install --no-interaction;
    fi

before_script:
 - vendor/bin/phpunit --version

script:
 - vendor/bin/phpunit

after_script:
  - bash <(curl -s https://codecov.io/bash)